# Generated by Django 4.2 on 2023-05-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='uid',
            new_name='user',
        ),
    ]
